# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3d66003a0d21cc8102b67da4e830e2ef6a5eca5e6089dd373430f7541a7e07a5e9ba8fbf291a99d17077f1ddfa9c5833fdedbd2f0b81a49f18b20aa3b69210

test:
  secret_key_base: 24d222ea761f7725cc2d586a0a141548dafef4f03b90a17eb40ce4da257afff12db68843a796d8b5c1b100981d6f9af45d225b8b1430ef8e63ecd0b6f60c1dde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
